### ISSUE TITLE
Not all data items have the proper padding and alignment

### ISSUE THREAD

**Issue by depryf** [imsweb/naaccr-xml#102]
NAACCR has a page specifying the alignment and padding of the data items:

http://datadictionary.naaccr.org/?c=9

For example, the new variable "lnSize" is supposed to be right justified, but it's not defined as such in dictionary.

Unfortunately, the dictionaries don't specify alignment and padding; they use padding rules for both (which sucks IMO):
```java
    // padding rules (default is rightBlank)
    public static final String NAACCR_PADDING_RIGHT_BLANK = "rightBlank";
    public static final String NAACCR_PADDING_LEFT_BLANK = "leftBlank";
    public static final String NAACCR_PADDING_RIGHT_ZERO = "rightZero";
    public static final String NAACCR_PADDING_LEFT_ZERO = "leftZero";
```

So a value of "Right justified, zero filled" in the document should correspond to an attribute "leftZero". A value of "Right justfified" should be "leftBlank".

One issue with this is that alignment makes no sense in XML (it does in flat file). So I think the first thing to do is to change NaaccrPatientConverter.writeItem() so it stops handling the two "blank" padding rules; it should only pad with 0 if needed.

Once that's done, then we should review all the dictionaries and set the correct attribute if it's missing.

I would start with the v18 dictionary using that NAACCR webpage. Then keep track of any item you modify and if that item exists in older dictionaries, then modify it there as well (I don't think we can easily access older version on the webpage.

**Comment by schadega** [comment]
Merge request submitted.

**Comment by depryf** [comment]
This has been merged.
