### ISSUE TITLE
PatientFlatWriter is writing new lines

### ISSUE THREAD

**Issue by agsong** [imsweb/naaccr-xml#104]
I was able to create a flat file in which one line ended at column 3889, and the next line was only 18936 characters. So basically a single line got split into two lines on the item followUpContactName.

**Comment by depryf** [comment]
@agsong I tried to reproduce this and I wasn't able to.  Every new line (either /r/n or just /n) are supposed to be replaced by a space when writing flat. I have a unit test for that (I updated it to include the followUpContactName).

Could you please try to reproduce this issue in DMS and tell me exactly what data is being sent to the library when this happens?

**Comment by agsong** [comment]
There are some \r characters that aren't followed by a \n. I found 7 instances on HI BETA (TSK-16632255).

**Comment by depryf** [comment]
Well, that would explain it. I was always under the impression that a \r by itself is not valid, but maybe it's a wrong assumption for this purpose.

I will add \r to end-of-lines characters being replaced then.

**Comment by depryf** [comment]
This is fixed an unit tested. Will be available in the next release!
