### ISSUE TITLE
ruralurbanContinuum2013 has no padding rule? 

### ISSUE THREAD

**Issue by agsong** [imsweb/naaccr-xml#106]
ruralurbanContinuum1993, ruralurbanContinuum2003, and ruralurbanContinuum2013 are all length 2. 1993 and 2003 are left zero padded, but 2013 doesn't define a padding rule. That seems suspicious, especially because we used to left zero pad this field in the old extracts in DMS.

**Comment by depryf** [comment]
@schadega I thought we review all the padding rules at some point. Maybe not. Can you please take a look at this when you have time? Thanks.

**Comment by depryf** [comment]
Never mind.

This is correct according to the current NAACCR specs: http://datadictionary.naaccr.org/default.aspx?c=9#3300

The 1993 and the 2003 are defined as left-zero-padded (Right justified, zero filled) but the 2013 doesn't define any padding rules.

I don't understand that and it seems very inconsistent, but we are following the NAACCR specs.

If SEER*DMS used to pad this fields in its NAACCR extract, then that was a mistake.
