### ISSUE TITLE
Update field ID for v18

### ISSUE THREAD

**Issue by schadega** [imsweb/naaccr-xml#119]
NAACCR sent out another round of changes for the v18 dictionary, and they've updated the field ID and name for lymphVascularInvasion (#1182):

Old ID: lymphVascularInvasion 
Old name: Lymph-vascular Invasion

New ID: lymphovascularInvasion 
New name: Lymphovascular Invasion

**Comment by depryf** [comment]
I have to contact NAACCR about this. They have to realize they can't just change NAACCR ID whenever they feel like it since it invalidates existing data files.

**Comment by depryf** [comment]
I talked to someone from NAACCR and their confirmed that the online NAACCR ID shouldn't have been updated when the name changed. They are going to revert that change. So nothing to change in the library...
