### ISSUE TITLE
Set naaccrId for NaaccrValidationError CODE_BAD_NAACCR_ID

### ISSUE THREAD

**Issue by schadega** [imsweb/naaccr-xml#122]
NaaccrValidationError has a naaccrId field, which is typically set to the ID of the item that caused the error. However, if the error is CODE_BAD_NAACCR_ID then the field is left null. This can make it difficult to report the details of the error in other applications, so the field should be set to the bad ID for this code.

**Comment by schadega** [comment]
The value field should also be set.

**Comment by depryf** [comment]
This has been merged.
