### ISSUE TITLE
Remove support for XZ compression

### ISSUE THREAD

**Issue by depryf** [imsweb/naaccr-xml#127]
When I started this library, the NAACCR XML standard was still very young and the biggest concern of the community was the size of the data files. Because of that, I found a library that does better compression that GZIP. It had a C implementation, and was fully compatible with 7zip. 

I really liked it (I still do) and so I added support for that compression (file extension xz) in the library.

A few years later, I now realize nobody (not even our SEER software) uses it. Maybe one of the reasons is that it's scary to see a ".xz" file instead of a well known ".gz" one... Anyhow, I would like to remove the dependency on that XZ library.

If a project wants to use that compression, that project can just define the dependency to that library itself and wrap the Input/Output stream into appropriate "Xz" streams. Still very doable. But I don't see the advantage of imposing that feature on everyone using this library, knowing that nobody really needs it.

**Comment by rpinder-zz** [comment]
If you remove .xz, will you now include dependency/support for .gz?  If I recall correctly (always suspect!), the utilities you've developed have options to compress inline, creating compact, compressed output, right ?    
Guess I'm thinking the library benefits from built in support for compression!!
( and thanks for all ya do on this ! )

**Comment by depryf** [comment]
GZ is "natively" supported by Java (no extra dependency needed for that). GZ is supported and will still be supported. This request won't affect that compression method.

I agree compression is very important; it's just that everyone knows and use GZ, nobody knows or seems willing to use XZ. So I just want to stop maintaining that one.

**Comment by depryf** [comment]
This work has been completed.
