### ISSUE TITLE
Investigate using a different XML library

### ISSUE THREAD

**Issue by depryf** [imsweb/naaccr-xml#137]
A long time ago I decided to use XStreams, and so far I am still very happy with it. But I think it would be a good idea to investigate using a more standard library like JACKSON.  This issue is not about replacing XStreams, just investigating the feasibility.

Here is a good description of JACKSON XML: https://stackify.com/java-xml-jackson/

**Comment by dckc** [comment]
I'm trying to write a little groovy utility, but I'm hitting `org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available`

any clues?

full context:

https://gist.github.com/dckc/1708af3dba3495cbc8af9b308eb5eabe

**Comment by depryf** [comment]
The "xpp3_min" library provides an implementation of the XmlPullParserFactory (you can verify that by opening the META-INF/services of that jar, you should see a "org.xmlpull.v1.XmlPullParserFactory" file). And so you should have everything you need for this.

Somehow the xpp3_min jar is not being properly set on the class path of the program.

You could try to do the following in your program:
```java
println (context.getResourceAsStream("/META-INF/services/org.xmlpull.v1.XmlPullParserFactory") == null)
```
If that returns null, then it's a class path issue. You are grabbing the correct JAR, but somehow they are not being properly put on the class path (or maybe just that specific resource file isn't).

**Comment by dckc** [comment]
aha... "the library needs to be loaded by the system classloader" -- https://codeday.me/en/qa/20190306/5613.html

**Comment by depryf** [comment]
Good find! Definitively not obvious!

**Comment by depryf** [comment]
I really don't have anything against XStream right now, and so I just can't justify spending any time in looking for another library... Maybe later...
