### ISSUE TITLE
Incorrect length error when loading v18 fixed-width file

### ISSUE THREAD

**Issue by isaackcr** [imsweb/naaccr-xml#143]
When I run the NAACCR XML Utility and choose "Flat to XML", browse to a Confidential fixed width file, I get the error message:
Error analysing file: invalid length for first record, expected 6934 but got 6154

In fact, record Type C should be 6154: http://datadictionary.naaccr.org/default.aspx?c=10#10

**Comment by depryf** [comment]
What a bad error, thanks for reporting it. I will fix it soon.

**Comment by depryf** [comment]
This is fixed, released in version 5.2.
