### ISSUE TITLE
Confidential Layout line length discrepancy

### ISSUE THREAD

**Issue by criderp** [imsweb/naaccr-xml#148]
The documentation for the record type field (http://datadictionary.naaccr.org/?c=10#10) says the confidential layout length is 6,154.  But the XML dictionary shows all items up to and including “Reserved 13” are included in the confidential layout, which would make the length 6,934.

It basically comes down to whether or not these items should be in the confidential layout:

Path Reporting Fac ID 1-5
Path Report Number 1-5
Path Date Spec Collect 1-5
Path Report Type 1-5
Path Ordering Fac No 1-5
Path Order Phys Lic No 1-5
Reserved 13

The NaaccrFormat constructor also sets the length to 6,154. Fabian said that is the correct length, though, so I think it's only the dictionary that is wrong.

**Comment by depryf** [comment]
Apparently those items used to be included in the confidential record type in version 16 but they got removed from that type in version 18. Very unexpected, probably why it was missed.

The fix will be released with version 5.4
