### ISSUE TITLE
JRE license: GPL 2 vs BSD

### ISSUE THREAD

**Issue by dckc** [imsweb/naaccr-xml#149]
This repo carries a BSD LICENSE file, but it includes a JRE from jdk.java.net, which seems to be GPL 2:

  The binaries are available under the GNU General Public License version 2, with the Classpath Exception. -- http://jdk.java.net/java-se-ri/12

**Comment by depryf** [comment]
Thanks for reporting this. We will look into that soon.

**Comment by depryf** [comment]
I will do more research on this but so far I don't see any issues with it.

Here is the JDK license for redistribution: http://openjdk.java.net/legal/gplv2+ce.html

Specifically, here is the part about the classpath exception:
```
As a special exception, the copyright holders of this library give you
    permission to link this library with independent modules to produce an
    executable, regardless of the license terms of these independent modules,
    and to copy and distribute the resulting executable under terms of your
    choice, provided that you also meet, for each linked independent module,
    the terms and conditions of the license of that module.
```

And so I don't see a problem with this standalone library (the independent module) having a BSD license while the JDK binaries retain their GPL 2 with classpath exception.

**Comment by dckc** [comment]
Perhaps the LICENCE file should clarify that it doesn't apply to everything in the repository?

**Comment by depryf** [comment]
Yes, that sounds like a good idea. I will look into that soon.

**Comment by depryf** [comment]
The license file has been modified to include a section about the JRE saying that the JRE falls under its own licensing and provides a link to find it online.
