### ISSUE TITLE
PatientXmlReader does not work with other namespaced elements after last Patient

### ISSUE THREAD

**Issue by isaackcr** [imsweb/naaccr-xml#167]
Consider this NAACCR XML file:

```
<NaaccrData baseDictionaryUri="http://naaccr.org/naaccrxml/naaccr-dictionary-180.xml" recordType="A" timeGenerated="2019-04-12T11:27:32.2581545-04:00" specificationVersion="1.4" xmlns="http://naaccr.org/naaccrxml"
            xmlns:test="https://www.naaccr.org/xmltest">
<Patient><Tumor></Tumor></Patient>
<test:NaaccrFileInfo author="somebody"><test:Description>My NAACCR File</test:Description></test:NaaccrFileInfo>
</NaaccrData>
```
Notice how there is an element after the last Patient called test:NaaccrFileInfo. Even if you configure the NaaccrStreamConfiguration object properly with all of the extra namespace element definitions, the PatientXmlReader.readPatient() will throw a NaaccrIOException with: "Unexpected tag: test:NaaccrFileInfo" after the last Patient is read because of this code in PatientXmlReader.readPatient():
```
    public Patient readPatient() throws NaaccrIOException {
        if (_context.extractTag(_reader.getNodeName()).equals(NAACCR_XML_TAG_ROOT))
            return null;

        if (!_context.extractTag(_reader.getNodeName()).equals(NAACCR_XML_TAG_PATIENT))
            throw new NaaccrIOException("Unexpected tag: " + _reader.getNodeName(), _context.getLineNumber());
```

Maybe I missed it, but there should be a way to read extra namespace elements after the last Patient, maybe adding a method like this:
```
Object nextPatientOrElement = PatientXmlReader.readPatientOrOtherElement(NaaccrFileInfo.class);
```

**Comment by depryf** [comment]
The specs only allow non-standard tags (the famous "any" in the XSD) to appear before the Patient tags, not after. The order matters for what appears under the "NaaccrData" tag and is the following:
1. File-level items (optional)
2. Non-standard tags (optional)
3. Patients (technically optional, but there really should be at least one!)

**Comment by isaackcr** [comment]
Good point, I forgot about the XSD: https://github.com/imsweb/naaccr-xml/blob/master/src/main/resources/xsd/naaccr_data_1.3.xsd

Nevermind then, I withdraw the request!
