### ISSUE TITLE
A few items have a mistake in their name in N18 dictionary

### ISSUE THREAD

**Issue by depryf** [imsweb/naaccr-xml#179]
I could let this go, but the name doesn't affect much in the NAACCR XML framework, and so I think I am going to fix them (because N18 is probably going to be used for a while still).

**Comment by depryf** [comment]
Here are the differences; I verified all of them against the official NAACCR documentation online, they were just mistakes in the library dictionary that nobody caught before.

- Item #833: "Date Sentinel Lymph Node Biopsy Flag" became "Date of Sentinel Lymph Node Biopsy Flag"
- Item #1114: "Mets at DX-Distant LN" became "Mets at Dx-Distant LN"
- Item #1182: "Lymph-vascular Invasion" became "Lymphovascular Invasion"
- Item #1756: "Date of Death--Canada Flag" became "Date of Death--CanadaFlag"
- Item #3875: "LN Distant: Mediastinal Scalene" became "LN Distant: Mediastinal, Scalene"

**Comment by rpinder-zz** [comment]
super... i was just gonn ask!  so you're makin the XML framework be in sync with the existing,current NAACCR dictionary ?  makes sense to me.

**Comment by depryf** [comment]
Yes. I am not sure how those became different than what NAACCR posts online. It's not worth figuring it out. I am just fixing it. Clearly this has not caused any issues for years, and so I doubt renaming those (the name, not the ID) is going to be a problem for anyone...

**Comment by depryf** [comment]
This work is completed. Will be released soon.
