### ISSUE TITLE
Patient ID missing leading 0

### ISSUE THREAD

**Issue by tuyetthieu2021** [imsweb/naaccr-xml#236]
Hi Fabian,
The PatientIdNumber in our flat file starts with leading '0'.  When we use the function 'write_naaccr_xml_macro' to convert the flat file to XML file, the patientIdNumber does not have the leading '0' which causes an error when running GenEdit (Patient ID Number (SEER CASENUM) [N0058]) because the length of this field is now less than 8.  < Item naaccrId="patientIdNumber" >1231456< /Item  >.

This is not an issue when using NorthCon V21 to convert a flat file to XML file.

Is it possible if the write_naaccr_xml_macro can keep the leading '0' in patientIdNumber field?  

Thank you for your help!
Tuyet Thieu

**Comment by depryf** [comment]
Hi Tuyet,

The write macro has no specific logic that would remove or add leading 0's.

And I just re-tested that case to be sure: I read an XML file using a the read macro (that file had a patient ID number starting with 0's), and then use the write macro to re-create the same file and ended up with the same patient ID number.

Could you please double-check that your patient ID numbers are properly padding in your SAS data set?

Can you also please confirm that you are using the write macro downloaded form this GitHub project, and not the full SAS program that is available on the NAACCR website?

**Comment by tuyetthieu2021** [comment]
Hi Fabian,

I have figured out the issue is in our dataset created before using the write macro downloaded from the GitHub project to convert the flat file to XML.  I fixed the dataset and there is no issue when using the write macro.

Thank you so much for your time looking to this question and quick response.

Best Regards,

Tuyet Thieu
