### ISSUE TITLE
Add option to not apply the padding rules

### ISSUE THREAD

**Issue by depryf** [imsweb/naaccr-xml#49]
This isn't a change to the specification or the format. 

People don't always use the items the way NAACCR defines them. For example, a registry might decide to change their abstracting tool to use "0000" for primary site (for some reason) and accept that value in the Central Registry. Clearly, this isn't a valid value according to the specs. But validation errors can always just be ignored if needed, they don't prevent anything.

The padding rules on the other hand have a direct impact on operations, they actually change the data. And right now there is no way to avoid that. So if NAACCR defines a field (say reporting facility) as being a 10 digits 0-left-padding field, but a registry wants to use their own ID ("HOSP123" for example), we will actually change the value (and it will become "000HOSP123"). 

I am not saying the behavior is wrong, because it isn't. But again, if we want this format to be well accepted, we need to be able to relax some of the constraints that didn't use to exist with flat file.

So I would like to add an new option to the library to allow the padding rules to be skipped.  The GUI will be changed to also show that new option. Default will be to apply the padding rules and so no changes in the current behavior of the library or the tool.

**Comment by isaackcr** [comment]
Agree, sounds like a good change.

**Comment by depryf** [comment]
This is implemented.
