### ISSUE TITLE
Missing URI attribute doesn't throw exception

### ISSUE THREAD

**Issue by schadega** [imsweb/naaccr-xml#77]
If the dictionaryUri attribute is missing from the NaaccrDictionary tag, the "readDictionary" method in "NaaccrXmlDictionaryUtils" doesn't catch this as an error, and it doesn't validate the dictionary. The "readDictionary" method calls the "validateDictionary" method if the URI is not null. If the URI is null, then the validation method is not called, no exception is thrown, and the dictionary is returned, as if the validation was successful, meaning that no other validation errors are caught either. If the URI is null, this should throw an exception.

**Comment by depryf** [comment]
Thanks for implementing those changes, they make complete sense. This will be available in the next release of the library (I don't think this requires a release right now).
